import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print('data cleaning and exploration')
data = pd.read_csv('passwords (1).csv')
df = pd.DataFrame(data)
print(df)
'''Exploratory data analysis'''
print('Head')
print(df.head())
print("Tail")
print(df.tail())
print("Information")
print(df.info())
print('Shape')
print(df.shape)
print('Data types')
print(df.dtypes)
print('Columns')
print(df.columns)
print('index')
print(df.index)
print('describe')
print(df.describe)
print(df['rank'].describe)
print('is null')
print(df.isnull)
print(df.isnull().sum())
print('drop null values')
print(df.dropna())
print('mean')
print(df['value'].mean())
print(df.groupby(['rank_alt'])['strength'].mean())
print('mode')
print(df['time_unit'].mode())
print('median')
print(df['strength'].median())
print('rename')
print(df.rename(columns={'font_size': 'font'}))
print('groupby')
print(df.groupby('password')['strength'].max())
print(df.groupby('password')['strength'].min())
#MATPLOT
print("Scatter plot")
x = df["strength"]
y = df["password"]
plt.title('Scatter plot')
plt.xlabel("strength")
plt.xticks(rotation=0)
plt.ylabel("password")
plt.yticks(rotation=0)
plt.scatter(x[1:40:1], y[1:40:1], color='r')
plt.show()
print('bar graph')
x = df["offline_crack_sec"]
y = df["password"]
plt.title('Bar graph')
plt.xlabel("offline_crack_sec")
plt.xticks(rotation=0)
plt.ylabel("password")
plt.yticks(rotation=0)
plt.bar(x[1:30:1], y[1:30:1], color='b')
plt.show()
print('grid plot')
x = df["strength"]
y = df["font_size"]
plt.title('grid plot')
plt.xlabel("strength")
plt.xticks(rotation=90)
plt.ylabel("font_size")
plt.plot(x[1:45:1], y[1:45:1])
plt.grid(color='b', linestyle='-', linewidth=1, axis='y')
plt.show()
print('scattered grid plot')
x = df["password"]
y = df["category"]
z = df["time_unit"]
plt.title('scattered grid plot')
plt.xlabel('password')
plt.xticks(rotation=45)
plt.ylabel('category')
plt.yticks(rotation=45)
plt.scatter(x[1:45:1], y[1:45:1])
plt.scatter(x[1:45:1], z[1:45:1])
plt.grid(color='k', linestyle=':', linewidth=0.5, axis="y")
plt.show()
data = df['rank']
keys = df['rank_alt']
print('pie chart')
plt.title("pie chart")
plt.pie(data[1:25:1], labels=keys[1:25:1])
plt.show()
#SEABORN
sns.countplot(x='font_size', data=df)
plt.title('count plot')
plt.show()
print('count plot')
sns.pairplot(df)
plt.title('pair plot')
plt.show()
print('pariplot')
sns.boxplot(x='offline_crack_sec', y='strength', data=df)
plt.title('box plot')
plt.show()
print('boxplot')
sns.scatterplot(x='offline_crack_sec', y='password', data=df)
plt.title('scatter plot')
plt.show()
print("scatter plot")
sns.lineplot(x='rank', y='strength', data=df)
plt.title('line plot')
plt.show()
print("line plot")
sns.relplot(x='strength', y='font_size', data=df)
plt.title('re plot')
plt.show()
print("re plot")
sns.jointplot(x='rank',y='value',data=df)
plt.title("joint plot")
plt.show()
print("joint plot")
sns.catplot(x='rank',y='password',data=df)
plt.title("categorical plot")
plt.show()
print("categorical plot")
sns.violinplot(x='password',y='strength',data=df)
plt.title("violin plot")
plt.show()
print("violin plot")