import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

print("Exploratory data analysis")
data = pd.read_csv('virat_kohli_centuries.csv')
df = pd.DataFrame(data)
print(df)
print('Head')
print(df.head())
print("Tail")
print(df.tail())
print("Information")
print(df.info())
print('Shape')
print(df.shape)
print('Data types')
print(df.dtypes)
print('Columns')
print(df.columns)
print('index')
print(df.index)
print('describe')
print(df.describe)
print(df['Against'].describe)
print('is null')
print(df.isnull)
print(df.isnull().sum())
print('drop null values')
print(df.dropna())
print('mean')
print(df['score'].mean())
print('groupby mean')
print(df.groupby(['strike_rate'])['score'].mean())
print('mode')
print(df['batting_order'].mode())
print('median')
print(df['innings'].median())
print('rename')
print(df.rename(columns={'Against': "opponent"}))
print('groupby')
print(df.groupby('score')['batting_order'].min())
#matplotlib
x = df["batting_order"]
y = df["score"]
plt.title('Scatter plot')
plt.xlabel("batting order")
plt.xticks(rotation=45)
plt.ylabel("score")
plt.yticks(rotation=20)
plt.scatter(x[1:50:1], y[1:50:1], color='b')
plt.show()
print('bar graph')
x = df["Against"]
y = df["score"]
plt.title('Virat vs other team score')
plt.xlabel("team name")
plt.xticks(rotation=0)
plt.ylabel("score")
plt.yticks(rotation=0)
plt.bar(x[1:30:1], y[1:30:1], color='k', linewidth=20)
plt.show()
print('grid plot')
x = df["century_number"]
y = df["strike_rate"]
plt.title('explosion of kohli')
plt.xlabel("no of century")
plt.xticks(rotation=0)
plt.ylabel("stike rate")
plt.yticks(rotation=0)
plt.plot(x[1:74:1], y[1:74:1])
plt.grid(color='b', linestyle='-', linewidth=1)
plt.show()
print('scattered grid plot')
x = df["score"]
y = df["strike_rate"]
z = df["innings"]
plt.title('Virat kohli Batting performance ')
plt.xticks(rotation=0)
plt.xlabel("score")
plt.yticks(rotation=0)
plt.ylabel("Strike rate")
plt.scatter(x[1:74:1], y[1:74:1])
plt.scatter(x[1:74:1], z[1:74:1])
plt.grid(color='y', linestyle='-.', linewidth=0.7)
plt.show()
data = df['batting_order']
keys = df['score']
print('pie chart')
plt.title('virat kohli batting performance at each position ')
plt.pie(data[1:74:1], labels=keys[1:74:1])
plt.show()
#seaborn
sns.countplot(y='venue', data=df)
plt.title('no of centuries at each venue')
print("count plot")
plt.show()
sns.pairplot(df)
plt.title("pair plot")
print("pair plot")
plt.show()
sns.boxplot(x="score", y="result", data=df)
plt.title("match winning contributions of kohli")
print("box plot")
plt.show()
sns.displot(x='score', y='format', data=df)
plt.title("score in each fromat")
plt.show()
print('distribution plot')
sns.scatterplot(x='venue', y='strike_rate', data=df)
plt.xticks(rotation=90)
plt.yticks(rotation=0)
plt.title("explosion of kohli at each venue")
plt.show()
print("scatter plot")
sns.lineplot(x='Against', y='strike_rate', data=df)
plt.xticks(rotation=0)
plt.yticks(rotation=0)
plt.title("Stike rate of kohli against each team")
plt.show()
print("line plot")
sns.relplot(x='batting_order', y='strike_rate', data=df)
plt.title("Virat's favourite batting order")
plt.show()
print("re plot")
sns.jointplot(x='man_of_the_match', y='score', data=df)
plt.title("award wining performances")
plt.show()
print("joint plot")
sns.catplot(x='innings', y='century_number', data=df)
plt.title("categorical plot")
plt.show()
sns.violinplot(x='strike_rate', y='captain', data=df)
plt.title("violin plot")
plt.show()
print("violin plot")
