import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

data = pd.read_csv('50_Startups.csv')
df = pd.DataFrame(data)
print(df)
'''Exploratory data analysis'''
print('Head')
print(df.head())
print("Tail")
print(df.tail())
print("Information")
print(df.info())
print('Shape')
print(df.shape)
print('Data types')
print(df.dtypes)
print('Columns')
print(df.columns)
print('index')
print(df.index)
print('describe')
print(df.describe)
print(df['State'].describe)
print('is null')
print(df.isnull)
print(df.isnull().sum())
print('mean')
print(df['Administration'].mean())
print(df.groupby(['Administration', 'Marketing Spend'])['Profit'].mean())
print('mode')
print(df['Administration'].mode())
print('median')
print(df['R&D Spend'].median())
print('rename')
print(df.rename(columns={'State': "Location"}))
print('groupby')
print(df.groupby('Marketing Spend')['Profit'].min())
print('drop null values')
print(df.dropna())
#MATPLOTLIB
x = df["R&D Spend"]
y = df["State"]
plt.title('Scatter plot')
plt.xlabel("R&D spend")
plt.xticks(rotation=45)
plt.ylabel("State")
plt.yticks(rotation=20)
plt.scatter(x[1:50:1], y[1:50:1], color='m')
plt.show()
print('bar graph')
x = df["Marketing Spend"]
y = df["State"]
plt.title('Bar graph')
plt.xlabel("Marketing Spend")
plt.xticks(rotation=90)
plt.ylabel("State")
plt.yticks(rotation=0)
plt.bar(x[1:50:1], y[1:50:1], color='c')
plt.show()
x = df["Administration"]
y = df["Profit"]
plt.title("Grid plot")
plt.xlabel("Administraation")
plt.ylabel("Profit")
plt.plot(x[1:50:1], y[1:50:1])
plt.grid(color='k', axis='x', linewidth=0.65, linestyle=':')
plt.show()
print("grid plot")
x = df["Administration"]
y = df["Profit"]
z = df["Marketing Spend"]
plt.title("plot grid plot")
plt.plot(x[1:50:1], y[1:50:1])
plt.plot(x[1:50:1], z[1:50:1])
plt.grid(color='m', axis='y', linewidth=0.5, linestyle='-.')
plt.show()
x = df["Administration"]
y = df["Profit"]
z = df["Marketing Spend"]
plt.title("Scattered grid plot")
plt.scatter(x[1:50:1], y[1:50:1])
plt.scatter(x[1:50:1], z[1:50:1])
plt.grid(color='m', axis='y', linewidth=0.5, linestyle='-.')
plt.show()
data = df["Administration"]
keys = df["State"]
plt.title("pie chart")
plt.pie(data[1:50:1], labels=keys[1:50:1])
plt.show()
#SEABORN
sns.countplot(x='R&D Spend', data=df)
plt.title("Count plot")
plt.show()
print('count plot')
sns.scatterplot(x='State', y='R&D Spend', data=df)
plt.title("Scatter plot")
plt.show()
print("Scatter plot")
sns.barplot(x='State', y='R&D Spend', data=df)
plt.title("Bar plot")
plt.show()
print("bar plot")
sns.boxplot(x='State', y='Marketing Spend', data=df)
plt.title("Box plot")
plt.show()
print("box plot")
sns.stripplot(x='State', y='Profit', data=df)
plt.title("strip plot")
plt.show()
print("strip plot")
sns.displot(x='R&D Spend', y='State', data=df)
plt.title("disribution plot")
plt.show()
print("disribution plot")
sns.scatterplot(x='State', y='Profit', data=df)
plt.title("Scatterplot")
plt.show()
print("Scatter plot")
sns.pairplot(df)
plt.title("pair plot")
plt.show()
print("Pair plot")
sns.lineplot(x='State', y='Administration', data=df)
plt.title('line plot')
plt.show()
print("line plot")
sns.jointplot(x='Profit', y='Administration', data=df)
plt.title("joint plot")
plt.show()
print("joint plot")
sns.catplot(x='Profit', y='State', data=df)
plt.title("categorical plot")
plt.show()
print('categrical plot')
sns.violinplot(x='Profit', y='State', data=df)
plt.title("violin plot")
plt.show()
print("violin plot")
