import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
print('data cleaning and exploration')
data=pd.read_csv('circuits.csv')
df=pd.DataFrame(data)
print(df)
'''Exploratory data analysis'''
print('Head')
print(df.head())
print("Tail")
print(df.tail())
print("Information")
print(df.info())
print('Shape')
print(df.shape)
print('Data types')
print(df.dtypes)
print('Columns')
print(df.columns)
print('index')
print(df.index)
print('describe')
print(df.describe)
print(df['location'].describe)
print('is null')
print(df.isnull)
print(df.isnull().sum())
print('mean')
print(df['lat'].mean())
print(df.groupby(['circuitId'])['lng'].mean())
print('mode')
print(df['location'].mode())
print('median')
print(df['circuitId'].median())
print('rename')
print(df.rename(columns={'url':"webpage"}))
print('groupby')
print(df.groupby('name')['location'].min())
print('drop null values')
print(df.dropna())
#MATPLOTLIB
x=df["name"]
y=df["country"]
plt.title('Scatter plot')
plt.xlabel("name of track")
plt.xticks(rotation=45)
plt.ylabel("location of the track")
plt.yticks(rotation=20)
plt.scatter(x[23:78:1],y[23:78:1],color='b')
plt.show()
print('bar graph')
x=df["location"]
y=df["country"]
plt.title('Bargraph')
plt.xlabel("location of the track")
plt.xticks(rotation=90)
plt.ylabel("country where track is there")
plt.yticks(rotation=0)
plt.bar(x[1:67:1],y[1:67:1],color='k')
plt.show()
print('grid plot')
x=df["circuitId"]
y=df["circuitRef"]
plt.title('Grid plot')
plt.xlabel("Id of circuit")
plt.ylabel("Reference name of circuit")
plt.plot(x[24:77:1],y[24:77:1],color='b')
plt.grid(color='b',linestyle='--',linewidth=1)
plt.show()
print('scattered grid plot')
x=df["name"]
y=df["location"]
z=df["country"]
plt.title('scatter grid plot')
plt.xticks(rotation=45)
plt.scatter(x[1:55:1],y[1:55:1])
plt.scatter(x[1:55:1],z[1:55:1])
plt.grid(color='m',linestyle=':',linewidth=0.5)
plt.show()
data=df['circuitId']
keys=df['country']
print('pie chart')
plt.title('no.of tracks in each country')
plt.pie(data[0:78:1],labels=keys[0:78:1])
plt.show()
#SEABORN
sns.countplot(x='name', data=df)
plt.show()
print("count plot")
sns.pairplot(df)
plt.show()
print('pariplot')
sns.boxplot(x='lng',y='lat',data=df)
plt.show()
print("box plot")
sns.displot(x='lng',y='lat',data=df)
plt.show()
print('distribution plot')
sns.scatterplot(x='lng',y='lat',data=df)
plt.show()
print("scatter plot")
sns.lineplot(x='lng',y='lat',data=df)
plt.show()
print("line plot")
sns.relplot(x='lng',y='lat',data=df)
plt.show()
print("replot")
sns.jointplot(x='lng',y='lat',data=df)
plt.show()
print("joint plot")
sns.catplot(x='lng',y='lat',data=df)
plt.show()
print("category plot")
sns.violinplot(x='lng',y='lat',data=df)
plt.show()
print("violin plot")